// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPDPAYtrfd2TlAygocuDkENXMjgfLRwY',
    appId: '1:623028009490:web:9acc579fd14ea5f10b76cb',
    messagingSenderId: '623028009490',
    projectId: 'android-app-df284',
    authDomain: 'android-app-df284.firebaseapp.com',
    databaseURL: 'https://android-app-df284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-app-df284.appspot.com',
    measurementId: 'G-TLH1NE9ZVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn6mkzKRm0C4dUblbq-vdNMQoO4cGqGRQ',
    appId: '1:623028009490:android:bfad6e327e5cf8a40b76cb',
    messagingSenderId: '623028009490',
    projectId: 'android-app-df284',
    databaseURL: 'https://android-app-df284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-app-df284.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANLTaWdASjiYcvTr2jjscpmcjnE0jx1NM',
    appId: '1:623028009490:ios:b07fba6e39429d840b76cb',
    messagingSenderId: '623028009490',
    projectId: 'android-app-df284',
    databaseURL: 'https://android-app-df284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-app-df284.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANLTaWdASjiYcvTr2jjscpmcjnE0jx1NM',
    appId: '1:623028009490:ios:cc1e75d0fcf8187f0b76cb',
    messagingSenderId: '623028009490',
    projectId: 'android-app-df284',
    databaseURL: 'https://android-app-df284-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'android-app-df284.appspot.com',
    iosBundleId: 'com.example.appProject.RunnerTests',
  );
}
